services:
  db:
    image: postgres
    container_name: postgres-document-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-doc:/var/lib/postgresql/data
    ports:
      - 5455:5432
    expose:
      - 5455
volumes:
  postgres-doc:
